### ISSUE TITLE
Package spec containing 'py_0' raises error

### ISSUE THREAD

**Issue by richardotis** [regro/conda-press#15]
`$ conda press --subdir linux-64 click=7.0=py_0`
[many dependencies are processed]
```
Building conda-forge/noarch::click==7.0=py_0 as dependency of click=7.0=py_0
Traceback (most recent call last):
  File "/home/rotis/anaconda3/envs/calphadpy3/bin/conda-press", line 3, in <module>
    main()
  File "/home/rotis/anaconda3/envs/calphadpy3/lib/python3.7/site-packages/conda_press/main.xsh", line 47, in main
    channels=channels)
  File "/home/rotis/anaconda3/envs/calphadpy3/lib/python3.7/site-packages/conda_press/condatools.xsh", line 783, in artifact_ref_dependency_tree_to_wheels
    _top=is_top
  File "/home/rotis/anaconda3/envs/calphadpy3/lib/python3.7/site-packages/conda_press/condatools.xsh", line 719, in package_to_wheel
    strip_symbols=strip_symbols,
  File "/home/rotis/anaconda3/envs/calphadpy3/lib/python3.7/site-packages/conda_press/condatools.xsh", line 686, in artifact_to_wheel
    wheel = Wheel(name, version, build_tag=build, python_tag=info.python_tag,
  File "/home/rotis/anaconda3/envs/calphadpy3/lib/python3.7/site-packages/conda_press/condatools.xsh", line 526, in python_tag
    elif pyver[0].isdigit():
IndexError: string index out of range

**Comment by scopatz** [comment]
Thanks for reporting @richardotis

**Comment by scopatz** [comment]
I can reproduce this.

**Comment by scopatz** [comment]
#19 is a potential fix here.  Also note that this is *a lot* faster if you also pass in `--skip-python`.  However, doing so will still suffer from #17.
