### ISSUE TITLE
No support for .conda files

### ISSUE THREAD

**Issue by 183amir** [regro/conda-press#66]
conda press does not seem to support the new version of conda-build packages `.conda` files and fails with:
```
Traceback (most recent call last):
  File "/home/amir/miniconda/bin/conda-press", line 4, in <module>
    main()
  File "/home/amir/miniconda/lib/python3.6/site-packages/conda_press/main.xsh", line 77, in main
    run_convert_wheel(ns.files, config)
  File "/home/amir/miniconda/lib/python3.6/site-packages/conda_press/main.xsh", line 91, in run_convert_wheel
    artifact_to_wheel(fname, config=config)
  File "/home/amir/miniconda/lib/python3.6/site-packages/conda_press/condatools.xsh", line 715, in artifact_to_wheel
    path, config=config
  File "/home/amir/miniconda/lib/python3.6/site-packages/conda_press/condatools.xsh", line 624, in from_tarball
    with tarfile.TarFile.open(path, mode=mode) as tf:
  File "/home/amir/miniconda/lib/python3.6/tarfile.py", line 1576, in open
    raise ReadError("file could not be opened successfully")
tarfile.ReadError: file could not be opened successfully
```

**Comment by scopatz** [comment]
Pull requests welcome!
